const mark = (key, label) => `<span class="glossary-term" data-glossary-key="${key}">${label}</span>`;

export const glossaryTerms = [
  {
    key: 'adoption',
    title: 'Adoption',
    summary: 'Aufnahme eines bereits vorhandenen Tieres aus Tierheim, Tierschutz oder Pflegestelle statt Kauf aus neuer Zucht oder Handel.',
    description: 'Aufnahme eines bereits vorhandenen Tieres aus Tierheim, Tierschutz oder Pflegestelle. Adoption vermeidet zusätzliche Nachfrage nach neu produzierten Haustieren.',
  },
  {
    key: 'aktivstall',
    title: 'Aktivstall',
    summary: 'Pferdehaltung, die Bewegung, Fressplätze und Ruhebereiche bewusst über Laufwege organisiert.',
    description: 'Pferdehaltung, bei der Futter, Wasser, Liegebereiche und Auslauf so angeordnet sind, dass Pferde sich im Alltag viel bewegen. Ein Aktivstall ist nur gut, wenn Herdenmanagement, Platz, Liegeflächen und Futterzugang wirklich passen.',
  },
  {
    key: 'alleinfutter',
    title: 'Alleinfutter',
    summary: 'Futter, das laut Zusammensetzung den vollständigen Bedarf eines Tieres dauerhaft decken soll.',
    description: 'Futter, das den vollständigen Bedarf eines Tieres dauerhaft decken soll. Besonders bei Katzen, Welpen, kranken oder alten Tieren ist entscheidend, ob es wirklich zur Art und Lebensphase passt.',
  },
  {
    key: 'albinismus',
    title: 'Albinismus',
    summary: 'Pigmentmangel, der bei Tieren je nach Art zu Lichtempfindlichkeit, Sehproblemen und Zuchtrisiken führen kann.',
    description: 'Pigmentmangel, der Haut, Augen und Fell oder Schuppen betrifft. Bei gezielter Zucht auf Albinismus können Lichtempfindlichkeit, Sehprobleme und weitere Belastungen entstehen.',
  },
  {
    key: 'anbindehaltung',
    title: 'Anbindehaltung',
    summary: 'Haltung, bei der ein Tier dauerhaft oder lange angebunden ist und sich kaum frei bewegen kann.',
    description: 'Haltung, bei der ein Tier dauerhaft oder über lange Zeiten angebunden ist. Bei Pferden verhindert sie Drehen, Liegen, freie Bewegung und normale Sozialkontakte.',
  },
  {
    key: 'apathie',
    title: 'Apathie',
    summary: 'Auffällige Teilnahmslosigkeit. Bei Tieren oft ein Warnsignal für Schmerz, Stress, Vergiftung oder schwere Krankheit.',
    description: 'Auffällige Teilnahmslosigkeit, Schwäche oder fehlende Reaktion auf Umweltreize. Bei Tieren ist Apathie oft ein Warnsignal für Schmerz, Stress, Vergiftung oder schwere Krankheit.',
  },
  {
    key: 'artgerecht',
    title: 'Artgerecht',
    summary: 'Haltung, die sich an den Bedürfnissen der Tierart orientiert: Platz, Sozialstruktur, Futter, Klima und Beschäftigung.',
    description: 'Haltung, die den natürlichen Bedürfnissen einer Tierart entspricht: Platz, Sozialstruktur, Ernährung, Beschäftigung, Klima, Rückzug und Gesundheitsvorsorge.',
  },
  {
    key: 'artgenosse',
    title: 'Artgenosse',
    summary: 'Tier derselben Art. Bei sozialen Tieren können andere Arten echte Artgenossen nicht ersetzen.',
    description: 'Ein Tier derselben Art. Für viele soziale Haustiere sind passende Artgenossen unverzichtbar; andere Arten ersetzen die eigene Sozialstruktur nicht zuverlässig.',
  },
  {
    key: 'artenschutz',
    title: 'Artenschutz',
    summary: 'Regeln zum Schutz gefährdeter Arten, etwa zu Herkunft, Handel, Nachweisen und Meldepflichten.',
    description: 'Schutz gefährdeter Tier- und Pflanzenarten. In der Heimtierhaltung betrifft Artenschutz vor allem Herkunftsnachweise, Handel, CITES-Papiere und Meldepflichten.',
  },
  {
    key: 'atemnot',
    title: 'Atemnot',
    summary: 'Erschwerte oder auffällige Atmung. Bei Tieren immer ernst nehmen und im Zweifel sofort tierärztlich abklären.',
    description: 'Erschwerte, schnelle, laute oder sichtbar angestrengte Atmung. Atemnot ist bei Tieren ein Notfallzeichen und sollte sofort tierärztlich abgeklärt werden.',
  },
  {
    key: 'beutetier',
    title: 'Beutetier',
    summary: 'Tierart, die in der Natur gejagt wird und Schwäche oft instinktiv verbirgt.',
    description: 'Tierart, die in der Natur selbst Beute sein kann. Viele Beutetiere verbergen Schmerz und Krankheit instinktiv, weshalb sichtbare Symptome oft spät auftreten.',
  },
  {
    key: 'boxenhaltung',
    title: 'Boxenhaltung',
    summary: 'Pferdehaltung in Einzelboxen. Nur vertretbar, wenn täglich viel Bewegung und Sozialkontakt gesichert sind.',
    description: 'Pferdehaltung in Einzelboxen. Sie kann soziale und körperliche Bedürfnisse stark einschränken und ist nur mit täglichem Auslauf, Bewegung und Sozialkontakt vertretbar.',
  },
  {
    key: 'brachyzephalie',
    title: 'Brachyzephalie',
    summary: 'Extrem verkürzte Schädelform, die häufig zu Atemnot, Augenproblemen und Hitzeempfindlichkeit führt.',
    description: 'Extrem verkürzte Schädelform. Bei Hunden und Katzen kann sie zu chronischer Atemnot, Augenproblemen, Zahnfehlstellungen und hoher Hitzeempfindlichkeit führen.',
  },
  {
    key: 'brachyzephales-atemwegssyndrom',
    title: 'Brachyzephales Atemwegssyndrom',
    summary: 'Atemwegsproblem kurzköpfiger Rassen durch verengte Nasen, Gaumen, Kehlkopf oder Luftröhre.',
    description: 'Atemwegsproblem kurzköpfiger Rassen. Verengte Nasenlöcher, verlängertes Gaumensegel, Kehlkopf- und Luftröhrenprobleme können Atmung, Schlaf und Belastbarkeit massiv einschränken.',
  },
  {
    key: 'brut-und-setzzeit',
    title: 'Brut- und Setzzeit',
    summary: 'Zeit, in der Wildtiere brüten oder Jungtiere setzen. Hunde sollten dann besonders kontrolliert und oft angeleint werden.',
    description: 'Zeit, in der Wildtiere brüten, Nachwuchs setzen oder Jungtiere aufziehen. Störungen durch freilaufende Hunde können in dieser Phase besonders schweren Schaden anrichten.',
  },
  {
    key: 'cites',
    title: 'CITES',
    summary: 'Washingtoner Artenschutzübereinkommen zum internationalen Handel mit gefährdeten Arten.',
    description: 'Washingtoner Artenschutzübereinkommen. Es regelt den internationalen Handel mit gefährdeten Tier- und Pflanzenarten und betrifft viele Reptilien, Schildkröten und Exoten.',
  },
  {
    key: 'chippen',
    title: 'Chippen',
    summary: 'Einsetzen eines Mikrochips unter die Haut, damit ein Tier eindeutig identifizierbar ist.',
    description: 'Einsetzen eines Mikrochips, meist unter die Haut am Hals. Der Chip trägt eine eindeutige Nummer; erst die Registrierung macht ihn für Rückvermittlung wirklich nützlich.',
  },
  {
    key: 'einzelgaenger',
    title: 'Einzelgänger',
    summary: 'Tier, das überwiegend allein lebt. Der Begriff wird bei Katzen oft fälschlich aus Einzeljagd abgeleitet.',
    description: 'Tier, das überwiegend allein lebt und Artgenossen nicht dauerhaft braucht. Bei Katzen wird der Begriff häufig falsch verwendet, weil Einzeljagd nicht automatisch Einzelhaltung bedeutet.',
  },
  {
    key: 'einzeljaeger',
    title: 'Einzeljäger',
    summary: 'Tier, das allein jagt. Das heißt nicht automatisch, dass es allein leben will.',
    description: 'Tiere, die allein jagen, etwa Katzen. Einzeljagd bedeutet nicht automatisch, dass ein Tier sozial isoliert leben möchte.',
  },
  {
    key: 'ellbogendysplasie',
    title: 'Ellbogendysplasie',
    summary: 'Fehlentwicklung des Ellbogengelenks, besonders bei größeren Hunden relevant und oft erblich mitbedingt.',
    description: 'Fehlentwicklung des Ellbogengelenks beim Hund. Sie kann Lahmheit, Schmerzen und Arthrose verursachen und ist bei vielen größeren Rassen ein wichtiger Punkt in Gesundheitsuntersuchungen der Zucht.',
  },
  {
    key: 'evidenzbasierte-medizin',
    title: 'Evidenzbasierte Medizin',
    summary: 'Medizin, die sich an überprüfbaren Studien, systematischer Erfahrung und fachlicher Diagnostik orientiert.',
    description: 'Medizinische Praxis, die sich an überprüfbaren Studien, systematischer Erfahrung und fachlicher Diagnostik orientiert, statt nur an Anekdoten oder Glaubenssätzen.',
  },
  {
    key: 'felv',
    title: 'FeLV',
    summary: 'Virusinfektion bei Katzen, die Immunsystem und Blutbildung schwächen und Tumore begünstigen kann.',
    description: 'Felines Leukämievirus. Eine ansteckende Virusinfektion bei Katzen, die Immunsystem und Blutbildung schwächen und Tumorerkrankungen begünstigen kann.',
  },
  {
    key: 'fiv',
    title: 'FIV',
    summary: 'Felines Immundefizienz-Virus. Wird vor allem durch tiefe Bissverletzungen übertragen.',
    description: 'Felines Immundefizienz-Virus, oft ungenau „Katzen-AIDS“ genannt. Es schwächt das Immunsystem und wird hauptsächlich durch tiefe Bissverletzungen übertragen.',
  },
  {
    key: 'fluchttier',
    title: 'Fluchttier',
    summary: 'Tier, das auf Gefahr zuerst mit Flucht reagiert und Festhalten oder Hochheben oft als Bedrohung erlebt.',
    description: 'Tier, das auf Gefahr instinktiv mit Flucht reagiert. Viele Fluchttiere erleben Hochheben, Festhalten, Lärm oder bedrängenden Kontakt als Stress.',
  },
  {
    key: 'freigang',
    title: 'Freigang',
    summary: 'Unbeaufsichtigter oder kontrollierter Zugang nach draußen, besonders bei Katzen ein wichtiger, aber riskanter Haltungsaspekt.',
    description: 'Zugang nach draußen. Bei Katzen kann Freigang Verhalten und Revierbedürfnisse erfüllen, bringt aber Risiken wie Verkehr, Krankheiten, Revierkämpfe und unkontrollierte Vermehrung mit sich.',
  },
  {
    key: 'freiflug',
    title: 'Freiflug',
    summary: 'Tägliche freie Flugzeit außerhalb des Käfigs in einem vogelsicheren Raum.',
    description: 'Tägliche freie Flugzeit außerhalb des Käfigs in einem vogelsicheren Raum. Für viele Heimvögel ist Freiflug Grundbedürfnis, nicht Zusatzbeschäftigung.',
  },
  {
    key: 'fruehkastration',
    title: 'Frühkastration',
    summary: 'Kastration vor der Geschlechtsreife, bei Katzen oft vor der ersten Rolligkeit.',
    description: 'Kastration vor der Geschlechtsreife. Bei Katzen bedeutet das häufig vor der ersten Rolligkeit und kann unkontrollierte Vermehrung sowie bestimmte Risiken deutlich reduzieren.',
  },
  {
    key: 'gendefekt',
    title: 'Gendefekt',
    summary: 'Erbliche Veränderung, die Gesundheit, Körperbau oder normale Funktion eines Tieres beeinträchtigen kann.',
    description: 'Erbliche Veränderung, die Gesundheit, Körperbau oder normale Funktion eines Tieres beeinträchtigen kann. In der Zucht können solche Defekte bewusst oder unbewusst weitergegeben werden.',
  },
  {
    key: 'globuli',
    title: 'Globuli',
    summary: 'Zuckerkügelchen aus der Homöopathie. In üblichen Potenzen ist kein Wirkstoff mehr nachweisbar.',
    description: 'Kleine Zuckerkügelchen aus der Homöopathie. Sie dienen als Träger für potenzierte Substanzen; in üblichen Potenzen ist kein Wirkstoff mehr nachweisbar.',
  },
  {
    key: 'got',
    title: 'GOT',
    summary: 'Gebührenordnung für Tierärzte. Sie regelt, wie tierärztliche Leistungen in Deutschland abgerechnet werden.',
    description: 'Gebührenordnung für Tierärzte. Sie regelt die Abrechnung tierärztlicher Leistungen in Deutschland und erklärt, warum Tierarztkosten nicht frei erfunden sind.',
  },
  {
    key: 'harnroehrenverschluss',
    title: 'Harnröhrenverschluss',
    summary: 'Blockierter Urinabsatz, besonders bei Katern lebensgefährlich und ein sofortiger Notfall.',
    description: 'Blockierter oder unmöglicher Urinabsatz. Besonders bei Katern kann ein Harnröhrenverschluss schnell lebensgefährlich werden und braucht sofortige tierärztliche Hilfe.',
  },
  {
    key: 'harnstopp',
    title: 'Harnstopp',
    summary: 'Alltagswort für blockierten oder unmöglichen Urinabsatz. Besonders bei Katern ein akuter Notfall.',
    description: 'Alltagswort für blockierten oder unmöglichen Urinabsatz, meist durch einen Harnröhrenverschluss. Wenn ein Tier nicht urinieren kann, ist das kein Beobachtungsfall, sondern ein sofortiger tierärztlicher Notfall.',
  },
  {
    key: 'harnwegserkrankung',
    title: 'Harnwegserkrankung',
    summary: 'Erkrankung von Blase, Harnröhre oder ableitenden Harnwegen. Bei Katzen oft ein Grund für Unsauberkeit.',
    description: 'Erkrankung von Blase, Harnröhre oder anderen ableitenden Harnwegen. Bei Katzen können Schmerzen, häufiges Aufsuchen des Katzenklos, Blut im Urin oder Unsauberkeit darauf hinweisen.',
  },
  {
    key: 'herdentier',
    title: 'Herdentier',
    summary: 'Tierart, die soziale Sicherheit aus einer Gruppe zieht. Alleinhaltung erzeugt oft massiven Stress.',
    description: 'Tierart, die in Gruppen lebt und soziale Sicherheit aus Herde oder Verband zieht. Bei Herdentieren ist isolierte Einzelhaltung meist stark belastend.',
  },
  {
    key: 'herkunftsnachweis',
    title: 'Herkunftsnachweis',
    summary: 'Nachweis der legalen Herkunft eines Tieres, besonders wichtig bei geschützten Arten und Exoten.',
    description: 'Dokument oder Beleg, der die legale Herkunft eines Tieres nachvollziehbar macht. Bei geschützten Arten können Herkunftsnachweise, CITES-Papiere oder behördliche Unterlagen entscheidend sein.',
  },
  {
    key: 'hecheln',
    title: 'Hecheln',
    summary: 'Schnelle Atmung über Maul und Zunge. Bei Hunden wichtig zur Kühlung, bei Stress oder Hitze aber ein Warnsignal.',
    description: 'Schnelle Atmung über Maul und Zunge. Hunde nutzen Hecheln zur Kühlung; starkes, hektisches oder anhaltendes Hecheln kann aber Stress, Schmerzen oder Überhitzung anzeigen.',
  },
  {
    key: 'hitzschlag',
    title: 'Hitzschlag',
    summary: 'Lebensgefährliche Überhitzung des Körpers. Bei Tieren zählt schnelles, kontrolliertes Kühlen und tierärztliche Hilfe.',
    description: 'Lebensgefährliche Überhitzung des Körpers. Warnzeichen sind starkes Hecheln, Schwäche, Taumeln, Erbrechen, Krämpfe oder Kollaps. Sofort tierärztlich handeln.',
  },
  {
    key: 'homoeopathie',
    title: 'Homöopathie',
    summary: 'Alternativmedizinisches Verfahren ohne belastbaren Wirksamkeitsnachweis über Placebo hinaus.',
    description: 'Alternativmedizinisches Verfahren aus dem 18. Jahrhundert. Für Homöopathie gibt es keinen belastbaren Wirksamkeitsnachweis über Placeboeffekte hinaus.',
  },
  {
    key: 'hufschmied',
    title: 'Hufschmied',
    summary: 'Fachperson für Hufpflege und Beschlag. Bei Pferden gehört regelmäßige Hufversorgung zu den Grundkosten.',
    description: 'Fachperson für Hufpflege, Korrektur und Beschlag. Bei Pferden gehört regelmäßige Hufversorgung zu den festen Gesundheits- und Haltungskosten.',
  },
  {
    key: 'hufrehe',
    title: 'Hufrehe',
    summary: 'Schmerzhafte Entzündung im Hufbereich des Pferdes, die schnell schwer und chronisch werden kann.',
    description: 'Schmerzhafte Erkrankung im Hufbereich des Pferdes. Hufrehe kann akut lebensgefährlich werden, bleibende Schäden verursachen und braucht sofortige fachliche Behandlung sowie gutes Fütterungs- und Haltungsmanagement.',
  },
  {
    key: 'hueftdysplasie',
    title: 'Hüftdysplasie',
    summary: 'Fehlentwicklung des Hüftgelenks, besonders bei größeren Hunderassen relevant.',
    description: 'Fehlentwicklung des Hüftgelenks, häufig erblich mitbedingt. Sie kann Schmerzen, Lahmheit und Arthrose verursachen und ist bei vielen großen Hunderassen relevant.',
  },
  {
    key: 'insulinschock',
    title: 'Insulinschock',
    summary: 'Gefährliche Unterzuckerung durch zu viel Insulinwirkung. Bei Hunden kann Xylit so etwas auslösen.',
    description: 'Gefährliche Unterzuckerung, wenn zu viel Insulin wirkt oder ausgeschüttet wird. Bei Hunden kann Xylit eine massive Insulinausschüttung auslösen und dadurch sehr schnell lebensbedrohlich werden.',
  },
  {
    key: 'kastration',
    title: 'Kastration',
    summary: 'Entfernung der Keimdrüsen. Verhindert Fortpflanzung und beendet die Hormonproduktion weitgehend.',
    description: 'Chirurgische Entfernung der Keimdrüsen, also Hoden oder Eierstöcke. Sie verhindert Fortpflanzung und beendet hormonbedingte Vorgänge wie Rolligkeit oder Markierdruck weitgehend.',
  },
  {
    key: 'kastrationspflicht',
    title: 'Kastrationspflicht',
    summary: 'Rechtliche Pflicht, bestimmte Katzen kastrieren zu lassen. In Deutschland meist kommunal geregelt.',
    description: 'Rechtliche Pflicht zur Kastration bestimmter Katzen, meist für Freigängerkatzen in einzelnen Kommunen oder Landkreisen. Es gibt keine bundesweite Einheitsregel; maßgeblich ist die örtliche Verordnung.',
  },
  {
    key: 'keimdruese',
    title: 'Keimdrüsen',
    summary: 'Hoden oder Eierstöcke. Sie bilden Keimzellen und wichtige Geschlechtshormone.',
    description: 'Hoden oder Eierstöcke. Keimdrüsen bilden Keimzellen und wichtige Geschlechtshormone; bei der Kastration werden sie entfernt.',
  },
  {
    key: 'kennzeichnungspflicht',
    title: 'Kennzeichnungspflicht',
    summary: 'Pflicht, ein Tier eindeutig zu kennzeichnen, meist per Mikrochip oder Tätowierung.',
    description: 'Pflicht, ein Tier eindeutig identifizierbar zu machen, meist durch Mikrochip oder Tätowierung. Bei Katzenschutzverordnungen gehört sie oft mit Registrierung und Kastration zusammen.',
  },
  {
    key: 'kognitive-dissonanz',
    title: 'Kognitive Dissonanz',
    summary: 'Innerer Widerspruch zwischen Selbstbild und Realität, den Menschen oft durch Ausreden oder Umdeutung entschärfen.',
    description: 'Psychologischer Spannungszustand, wenn Verhalten, Fakten und Selbstbild nicht zusammenpassen. Menschen lösen ihn oft durch Ausreden, Umdeutung oder Schuldverschiebung.',
  },
  {
    key: 'kollaps',
    title: 'Kollaps',
    summary: 'Plötzlicher Zusammenbruch oder starke Kreislaufschwäche. Bei Tieren immer ernst nehmen.',
    description: 'Plötzlicher Zusammenbruch, starke Schwäche oder Kreislaufversagen. Kollaps kann viele Ursachen haben, etwa Schmerz, Hitze, Herzprobleme, Vergiftung oder Blutverlust, und sollte sofort tierärztlich abgeklärt werden.',
  },
  {
    key: 'krampfanfall',
    title: 'Krampfanfall',
    summary: 'Unkontrollierte Muskelkrämpfe oder Bewusstseinsstörung. Nach einem Anfall tierärztlich abklären lassen.',
    description: 'Anfall mit unkontrollierten Muskelbewegungen, Bewusstseinsveränderung, Speicheln oder Orientierungslosigkeit. Einen Krampfanfall sollte man sicher begleiten, nicht festhalten und anschließend tierärztlich abklären lassen.',
  },
  {
    key: 'leinenpflicht',
    title: 'Leinenpflicht',
    summary: 'Pflicht, Hunde in bestimmten Gebieten oder Zeiten angeleint zu führen. Regeln sind regional verschieden.',
    description: 'Pflicht, Hunde an der Leine zu führen. Leinenpflichten unterscheiden sich je nach Bundesland, Kommune, Jahreszeit und Gebiet, etwa während Brut- und Setzzeiten oder in Naturschutzbereichen.',
  },
  {
    key: 'magendrehung',
    title: 'Magendrehung',
    summary: 'Lebensgefährlicher Notfall beim Hund, bei dem sich der Magen verdreht und aufgast.',
    description: 'Lebensgefährlicher Notfall beim Hund. Der Magen dreht sich und gast auf; typische Warnzeichen sind Unruhe, erfolgloses Würgen, harter Bauch und Kreislaufprobleme.',
  },
  {
    key: 'mammatumor',
    title: 'Mammatumor',
    summary: 'Tumor der Milchleiste. Bei Katzen und Hündinnen kann Kastration das Risiko je nach Zeitpunkt senken.',
    description: 'Tumor der Milchleiste. Bei Katzen und Hündinnen können Mammatumoren gut- oder bösartig sein; Kastration kann das Risiko je nach Tierart und Zeitpunkt deutlich beeinflussen.',
  },
  {
    key: 'kolik',
    title: 'Kolik',
    summary: 'Sammelbegriff für Bauchschmerzen beim Pferd. Kann harmlos beginnen, aber lebensgefährlich werden.',
    description: 'Sammelbegriff für Bauchschmerzen beim Pferd. Koliken können verschiedene Ursachen haben und müssen wegen Lebensgefahr immer ernst genommen werden.',
  },
  {
    key: 'mauser',
    title: 'Mauser',
    summary: 'Natürlicher Federwechsel bei Vögeln, der Energie kostet und mehrere Wochen dauern kann.',
    description: 'Natürlicher Federwechsel bei Vögeln. Er dauert oft mehrere Wochen, kostet Energie und kann Verhalten und Stimmung beeinflussen.',
  },
  {
    key: 'meldepflicht',
    title: 'Meldepflicht',
    summary: 'Pflicht, bestimmte Tiere oder Haltungen bei einer Behörde anzumelden, etwa aus Artenschutzgründen.',
    description: 'Pflicht, bestimmte Tiere, Haltungen oder Nachweise bei einer Behörde anzumelden. In der Heimtierhaltung betrifft das vor allem artgeschützte Exoten.',
  },
  {
    key: 'metaanalyse',
    title: 'Metaanalyse',
    summary: 'Studie, die Ergebnisse mehrerer einzelner Studien zusammen auswertet.',
    description: 'Wissenschaftliche Auswertung, die Ergebnisse mehrerer einzelner Studien zusammenführt. Eine gute Metaanalyse kann belastbarer sein als eine einzelne Studie, hängt aber stark von Qualität und Auswahl der einbezogenen Studien ab.',
  },
  {
    key: 'metabolische-knochenerkrankung',
    title: 'Metabolische Knochenerkrankung',
    summary: 'Knochenerweichung bei Reptilien, meist durch UV-B-, Vitamin-D3- oder Kalziummangel.',
    description: 'Knochenerweichung bei Reptilien, oft durch fehlende UV-B-Strahlung, Vitamin-D3- oder Kalziummangel. Sie führt zu Verformungen, Schmerzen und schweren Organschäden.',
  },
  {
    key: 'nachtaktiv',
    title: 'Nachtaktiv',
    summary: 'Tier ist vor allem nachts aktiv. Tagsüberes Wecken bedeutet oft Stress.',
    description: 'Tier ist vor allem in Dämmerung oder Nacht aktiv. Bei nachtaktiven Tieren bedeutet tagsüberes Wecken häufig Stress und widerspricht dem natürlichen Rhythmus.',
  },
  {
    key: 'notdienst',
    title: 'Tierärztlicher Notdienst',
    summary: 'Tierärztliche Versorgung außerhalb normaler Sprechzeiten. Immer telefonisch bestätigen, bevor du losfährst.',
    description: 'Tierärztliche Versorgung außerhalb normaler Sprechzeiten. Notdienste sind regional organisiert und sollten immer telefonisch bestätigt werden, bevor man losfährt.',
  },
  {
    key: 'notfallfonds',
    title: 'Notfallfonds',
    summary: 'Zurückgelegtes Geld für unerwartete Tierarztkosten, damit Behandlung nicht am Kontostand scheitert.',
    description: 'Zurückgelegtes Geld für unerwartete Tierarztkosten. Ein Notfallfonds verhindert, dass Diagnose oder Behandlung im Ernstfall am Kontostand scheitern.',
  },
  {
    key: 'nosoden',
    title: 'Nosoden',
    summary: 'Homöopathische Mittel aus krankheitsbezogenem Ausgangsmaterial. Kein Ersatz für Impfung, Diagnostik oder Behandlung.',
    description: 'Homöopathische Mittel, deren Ausgangsmaterial aus krankheitsbezogenen Stoffen stammen kann. Nosoden sind kein Ersatz für Impfungen, tierärztliche Diagnostik oder wirksame Behandlung.',
  },
  {
    key: 'obligater-karnivor',
    title: 'Obligater Karnivor',
    summary: 'Tierart, deren Stoffwechsel auf tierische Nahrung spezialisiert ist. Katzen sind obligate Karnivoren.',
    description: 'Tierart, deren Stoffwechsel auf tierische Nahrung und bestimmte Nährstoffprofile spezialisiert ist. Katzen sind obligate Karnivoren und keine kleinen Hunde.',
  },
  {
    key: 'obligat-sozial',
    title: 'Obligat sozial',
    summary: 'Tierart braucht Artgenossen zwingend. Alleinhaltung ist dann kein kleiner Kompromiss.',
    description: 'Tierart braucht passende Artgenossen zwingend. Bei obligat sozialen Tieren ist Alleinhaltung kein kleiner Kompromiss, sondern ein Tierschutzproblem.',
  },
  {
    key: 'offenstall',
    title: 'Offenstall',
    summary: 'Pferdehaltung mit Bewegungsfreiheit, Unterstand, Auslauf und Sozialkontakt.',
    description: 'Pferdehaltung, bei der Tiere Zugang zu Unterstand, Auslauf und oft Weide haben. Gute Offenstallkonzepte fördern Bewegung, Sozialkontakt und selbstbestimmtes Verhalten.',
  },
  {
    key: 'osteochondrodysplasie',
    title: 'Osteochondrodysplasie',
    summary: 'Erbliche Knorpel- und Knochenerkrankung, bekannt bei Scottish-Fold-Katzen.',
    description: 'Erbliche Knorpel- und Knochenerkrankung. Bei Scottish-Fold-Katzen hängt sie mit den gefalteten Ohren zusammen und kann lebenslange Schmerzen verursachen.',
  },
  {
    key: 'parvovirose',
    title: 'Parvovirose',
    summary: 'Schwere Virusinfektion bei Hunden, besonders für Welpen lebensgefährlich.',
    description: 'Schwere, hochansteckende Virusinfektion bei Hunden. Besonders Welpen können durch Erbrechen, Durchfall, Dehydrierung und Kreislaufversagen sterben.',
  },
  {
    key: 'pbfd',
    title: 'PBFD',
    summary: 'Ansteckende Viruserkrankung bei Papageienvögeln, die Gefieder, Schnabel und Immunsystem angreifen kann.',
    description: 'Psittacine Beak and Feather Disease. Eine ansteckende Viruserkrankung bei Papageienvögeln, die Gefieder, Schnabel und Immunsystem angreifen kann.',
  },
  {
    key: 'permethrin',
    title: 'Permethrin',
    summary: 'Wirkstoff in manchen Hunde-Flohmitteln. Für Katzen kann er lebensgefährlich giftig sein.',
    description: 'Insektizid, das in manchen Hunde-Flohmitteln vorkommt. Für Katzen kann Permethrin wegen ihres Stoffwechsels lebensgefährlich giftig sein.',
  },
  {
    key: 'pflegestelle',
    title: 'Pflegestelle',
    summary: 'Vorübergehendes Zuhause für ein Tier, bis eine dauerhafte Vermittlung gefunden ist.',
    description: 'Vorübergehendes Zuhause für ein Tier aus dem Tierschutz, bis eine dauerhafte Vermittlung gefunden ist. Pflegestellen entlasten Tierheime und lernen Tiere im Alltag kennen.',
  },
  {
    key: 'placebo-effekt',
    title: 'Placebo-Effekt',
    summary: 'Wahrgenommene Besserung durch Erwartung, Beobachtung oder Begleitumstände statt durch einen wirksamen Stoff.',
    description: 'Wahrgenommene Besserung durch Erwartung, veränderte Beobachtung oder Begleitumstände statt durch einen wirksamen Stoff. Bei Tieren spielt vor allem die menschliche Interpretation eine Rolle.',
  },
  {
    key: 'potenzierung',
    title: 'Potenzierung',
    summary: 'Homöopathisches Verdünnen und Verschütteln, bei dem der Ausgangsstoff rechnerisch oft nicht mehr vorhanden ist.',
    description: 'Homöopathisches Verfahren aus Verdünnen und Verschütteln. In hohen Potenzen ist vom Ausgangsstoff rechnerisch kein Molekül mehr enthalten.',
  },
  {
    key: 'd-und-c-potenz',
    title: 'D- und C-Potenz',
    summary: 'Homöopathische Verdünnungsstufen: D bedeutet 1:10 pro Schritt, C bedeutet 1:100 pro Schritt.',
    description: 'Homöopathische Verdünnungsangabe. D-Potenzen werden pro Schritt im Verhältnis 1:10 verdünnt, C-Potenzen im Verhältnis 1:100. Hohe Potenzen enthalten rechnerisch oft keinen Ausgangsstoff mehr.',
  },
  {
    key: 'ptfe',
    title: 'PTFE',
    summary: 'Beschichtungsstoff, der bei Überhitzung giftige Dämpfe bilden kann. Für Vögel besonders gefährlich.',
    description: 'Polytetrafluorethylen, bekannt aus Antihaftbeschichtungen. Bei Überhitzung können Dämpfe entstehen, die für Vögel extrem schnell tödlich sein können.',
  },
  {
    key: 'pyometra',
    title: 'Pyometra',
    summary: 'Gebärmuttervereiterung. Lebensbedrohlich und bei unkastrierten Hündinnen und Katzen ein Notfall.',
    description: 'Gebärmuttervereiterung. Sie tritt besonders bei unkastrierten Hündinnen und Katzen auf und ist lebensbedrohlich, wenn sie nicht schnell behandelt wird.',
  },
  {
    key: 'qualzucht',
    title: 'Qualzucht',
    summary: 'Zucht auf Merkmale, die Schmerzen, Leiden, Schäden oder eingeschränkte normale Funktionen verursachen.',
    description: 'Zucht auf Merkmale, die Schmerzen, Leiden, Schäden oder eingeschränkte normale Funktionen verursachen. Qualzucht ist nach § 11b TierSchG verboten, bleibt aber praktisch schwer durchzusetzen.',
  },
  {
    key: 'rassemerkmal',
    title: 'Rassemerkmal',
    summary: 'Züchterisch gewünschtes Merkmal einer Rasse. Nicht jedes Rassemerkmal ist gesund oder harmlos.',
    description: 'Züchterisch gewünschtes Merkmal einer Rasse. Ein Rassemerkmal kann äußerlich beliebt sein und trotzdem Gesundheit, Bewegung, Atmung oder Sinneswahrnehmung belasten.',
  },
  {
    key: 'raufutter',
    title: 'Raufutter',
    summary: 'Strukturreiches Futter wie Heu oder Gras, das für Pferde und viele Pflanzenfresser zentral ist.',
    description: 'Strukturreiches Futter wie Heu, Gras oder Strohanteile. Für Pferde und viele Pflanzenfresser ist ausreichendes Raufutter wichtig für Verdauung, Beschäftigung und normale Fresszeiten.',
  },
  {
    key: 'registrierungspflicht',
    title: 'Registrierungspflicht',
    summary: 'Pflicht, ein gekennzeichnetes Tier in einem Register einzutragen, damit es zugeordnet werden kann.',
    description: 'Pflicht, ein gekennzeichnetes Tier mit Halterdaten in einem Haustierregister einzutragen. Erst die Registrierung macht Chip oder Tätowierung für Rückvermittlung und Vollzug wirklich nutzbar.',
  },
  {
    key: 'rolligkeit',
    title: 'Rolligkeit',
    summary: 'Paarungsbereite Zyklusphase bei Katzen, oft mit Stress, Rufen und Unruhe.',
    description: 'Paarungsbereite Zyklusphase bei unkastrierten Katzen. Sie kann alle zwei bis drei Wochen auftreten und mit starkem Stress, Rufen, Unruhe und Gesundheitsrisiken verbunden sein.',
  },
  {
    key: 'sachkunde',
    title: 'Sachkunde',
    summary: 'Nachweisbares Fachwissen zur Haltung, Versorgung und Sicherheit bestimmter Tiere.',
    description: 'Nachweisbares Fachwissen zur Haltung, Versorgung und Sicherheit bestimmter Tiere. Bei anspruchsvollen oder gefährlichen Arten reicht Begeisterung nicht aus.',
  },
  {
    key: 'schutzgebuehr',
    title: 'Schutzgebühr',
    summary: 'Betrag bei Adoption, der Versorgungskosten mitträgt und kein normaler Kaufpreis ist.',
    description: 'Betrag, der bei Adoption eines Tierschutztieres gezahlt wird. Er deckt einen Teil von Kastration, Impfung, Chip, Futter und tierärztlicher Versorgung und ist kein normaler Kaufpreis.',
  },
  {
    key: 'schutzvertrag',
    title: 'Schutzvertrag',
    summary: 'Adoptionsvertrag, der Rückgabe, Nachkontrolle und Haltungsbedingungen regeln kann.',
    description: 'Vertrag bei der Vermittlung eines Tierschutztieres. Er kann Rückgaberecht, Nachkontrolle, Kastration, Haltungsvorgaben und Verantwortung nach der Adoption regeln.',
  },
  {
    key: 'patenschaft',
    title: 'Patenschaft',
    summary: 'Regelmäßige finanzielle oder praktische Unterstützung für ein Tier, ohne es selbst zu halten.',
    description: 'Regelmäßige finanzielle oder praktische Unterstützung für ein Tier, ohne es selbst zu halten. Patenschaften helfen besonders alten, kranken oder schwer vermittelbaren Tieren.',
  },
  {
    key: 'phytotherapie',
    title: 'Phytotherapie',
    summary: 'Pflanzenheilkunde. Kann je nach Mittel wirksame Stoffe enthalten, braucht aber fachliche Abklärung.',
    description: 'Pflanzenheilkunde. Anders als Homöopathie kann Phytotherapie wirksame Stoffe enthalten; gerade deshalb sind Dosierung, Wechselwirkungen und tierärztliche Abklärung wichtig.',
  },
  {
    key: 'schwarmvogel',
    title: 'Schwarmvogel',
    summary: 'Vogelart, die in Gruppen lebt und Artgenossen braucht.',
    description: 'Vogelart, die in Gruppen lebt und passende Artgenossen braucht. Wellensittiche, Nymphensittiche und Zebrafinken sind typische Schwarmvögel.',
  },
  {
    key: 'skorbut',
    title: 'Skorbut',
    summary: 'Krankheit durch Vitamin-C-Mangel. Bei Meerschweinchen relevant, weil sie Vitamin C nicht selbst bilden.',
    description: 'Krankheit durch Vitamin-C-Mangel. Meerschweinchen können Vitamin C nicht selbst bilden und brauchen deshalb regelmäßig geeignetes Frischfutter.',
  },
  {
    key: 'sozialisation',
    title: 'Sozialisation',
    summary: 'Lernphase und Erfahrungssammlung, in der Tiere Umwelt, Menschen und Artgenossen kennenlernen.',
    description: 'Lernphase und Erfahrungssammlung, in der Tiere Umwelt, Menschen, Artgenossen und Alltagssituationen kennenlernen. Fehlende Sozialisation kann später Angst und Problemverhalten fördern.',
  },
  {
    key: 'sterilisation',
    title: 'Sterilisation',
    summary: 'Durchtrennung von Ei- oder Samenleitern. Das Tier wird unfruchtbar, Hormone bleiben aktiv.',
    description: 'Durchtrennung der Ei- oder Samenleiter. Das Tier wird unfruchtbar, aber Hormonproduktion, Rolligkeit, Markierverhalten und Paarungsdrang bleiben weitgehend bestehen.',
  },
  {
    key: 'stereotypie',
    title: 'Stereotypie',
    summary: 'Zwanghaft wiederholtes Verhalten ohne sinnvollen Zweck, oft Zeichen von chronischem Stress.',
    description: 'Sich wiederholende, zwanghafte Verhaltensweisen ohne erkennbaren Zweck. Beispiele sind Koppen, Weben, Federrupfen oder stereotypes Kopfwippen.',
  },
  {
    key: 'systematischer-review',
    title: 'Systematischer Review',
    summary: 'Übersichtsarbeit, die Studien nach vorher festgelegten Kriterien sucht, bewertet und zusammenfasst.',
    description: 'Wissenschaftliche Übersichtsarbeit, die vorhandene Studien nach vorher festgelegten Kriterien sucht, auswählt, bewertet und zusammenfasst. Systematische Reviews sind wichtig, um Einzelstudien nicht überzubewerten.',
  },
  {
    key: 'streunerkatze',
    title: 'Streunerkatze',
    summary: 'Frei lebende Katze ohne verlässliche Versorgung, oft Nachkomme unkastrierter Hauskatzen.',
    description: 'Frei lebende Katze ohne verlässliche menschliche Versorgung. Viele Streunerkatzen sind Nachkommen unkastrierter Freigängerkatzen und leiden unter Krankheit, Hunger und Verletzungen.',
  },
  {
    key: 'taurin',
    title: 'Taurin',
    summary: 'Für Katzen essenzieller Nährstoff, wichtig für Herz, Augen, Stoffwechsel und Fortpflanzung.',
    description: 'Für Katzen essenzieller Nährstoff. Taurin ist wichtig für Herz, Netzhaut, Gallensäuren, Fortpflanzung und Entwicklung und muss zuverlässig im Futter vorhanden sein.',
  },
  {
    key: 'theobromin',
    title: 'Theobromin',
    summary: 'Stoff aus Kakao und Schokolade, der für Hunde giftig sein kann.',
    description: 'Stoff aus Kakao und Schokolade. Hunde bauen Theobromin langsam ab; schon kleinere Mengen dunkler Schokolade können gefährlich werden.',
  },
  {
    key: 'tierheim',
    title: 'Tierheim',
    summary: 'Einrichtung, die abgegebene, gefundene oder beschlagnahmte Tiere versorgt und vermittelt.',
    description: 'Einrichtung, die gefundene, abgegebene, ausgesetzte oder beschlagnahmte Tiere versorgt und vermittelt. Tierheime sind oft überlastet und auf Unterstützung angewiesen.',
  },
  {
    key: 'tierheilpraktiker',
    title: 'Tierheilpraktiker',
    summary: 'Nicht geschützte Berufsbezeichnung. Kein Ersatz für tierärztliche Diagnostik und Behandlung.',
    description: 'Nicht geschützte Berufsbezeichnung in Deutschland. Ausbildung und Qualität sind uneinheitlich; Tierheilpraktiker ersetzen keine tierärztliche Diagnostik und Behandlung.',
  },
  {
    key: 'tierschg',
    title: 'TierSchG',
    summary: 'Deutsches Tierschutzgesetz. Es regelt Grundpflichten, Verbote und Verantwortlichkeiten im Umgang mit Tieren.',
    description: 'Deutsches Tierschutzgesetz. Es regelt Grundpflichten, Verbote und Verantwortlichkeiten im Umgang mit Tieren, darunter Haltung, Pflege, Zucht und Aussetzen.',
  },
  {
    key: 'tierschutz-hundeverordnung',
    title: 'Tierschutz-Hundeverordnung',
    summary: 'Deutsche Verordnung mit Mindestanforderungen an Hundehaltung, etwa Auslauf, Sozialkontakt und Zwingerhaltung.',
    description: 'Deutsche Verordnung mit Mindestanforderungen an Hundehaltung. Sie betrifft unter anderem Auslauf, Sozialkontakt, Betreuung, Zwingerhaltung und Witterungsschutz.',
  },
  {
    key: 'tierklinik',
    title: 'Tierklinik',
    summary: 'Tiermedizinische Einrichtung mit erweitertem Leistungsangebot, oft wichtig bei Notfällen außerhalb normaler Praxiszeiten.',
    description: 'Tiermedizinische Einrichtung mit erweitertem Leistungsangebot. Tierkliniken sind bei schweren Notfällen, Operationen oder Nacht- und Wochenendversorgung oft die richtige Anlaufstelle.',
  },
  {
    key: 'tierphysiotherapie',
    title: 'Tierphysiotherapie',
    summary: 'Gezielte Bewegungstherapie und Rehabilitation für Tiere, etwa nach OPs oder bei Gelenkproblemen.',
    description: 'Gezielte Bewegungstherapie, Rehabilitation und Funktionsarbeit für Tiere. Sie kann nach Operationen, bei Gelenkproblemen, Schmerzmanagement oder altersbedingten Einschränkungen sinnvoll sein, ersetzt aber keine tierärztliche Diagnose.',
  },
  {
    key: 'tnr',
    title: 'TNR',
    summary: 'Trap-Neuter-Return: Streunerkatzen einfangen, kastrieren und wieder zurücksetzen.',
    description: 'Trap-Neuter-Return. Methode zur Kontrolle von Streunerkatzen: einfangen, kastrieren, medizinisch versorgen und wieder an betreute Futterstellen zurücksetzen.',
  },
  {
    key: 'traechtigkeit',
    title: 'Trächtigkeit',
    summary: 'Schwangerschaft bei Tieren. Ungewollte Trächtigkeit erzeugt Verantwortung und Gesundheitsrisiken.',
    description: 'Schwangerschaft bei Tieren. Ungewollte Trächtigkeit bedeutet Gesundheitsrisiken, Kosten, Verantwortung für Nachwuchs und oft zusätzliche Belastung für Tierheime.',
  },
  {
    key: 'tvt',
    title: 'TVT',
    summary: 'Tierärztliche Vereinigung für Tierschutz. Sie veröffentlicht fachliche Merkblätter zur Tierhaltung.',
    description: 'Tierärztliche Vereinigung für Tierschutz. Sie veröffentlicht fachliche Merkblätter, Leitlinien und Einschätzungen zu artgerechter Tierhaltung.',
  },
  {
    key: 'uv-b',
    title: 'UV-B-Strahlung',
    summary: 'Ultraviolette Strahlung, die viele Reptilien und Vögel für Vitamin-D3-Bildung und normale Wahrnehmung brauchen.',
    description: 'Ultraviolette Strahlung. Viele Reptilien brauchen UV-B für Vitamin-D3-Bildung und Kalziumstoffwechsel; Vögel nutzen UV-Licht auch für ihre Farbwahrnehmung.',
  },
  {
    key: 'unsauberkeit',
    title: 'Unsauberkeit',
    summary: 'Urinieren oder Kotabsatz außerhalb des vorgesehenen Platzes. Bei Katzen oft Warnsignal statt Protest.',
    description: 'Urinieren oder Kotabsatz außerhalb des vorgesehenen Platzes. Bei Katzen ist Unsauberkeit selten bloßer Protest; häufig stecken Schmerzen, Stress, Harnwegserkrankungen oder ungeeignete Toilettenbedingungen dahinter.',
  },
  {
    key: 'vegane-tierernaehrung',
    title: 'Vegane Tierernährung',
    summary: 'Tierernährung ohne tierische Bestandteile. Bei Haustieren zählt zuerst der Bedarf der Tierart, nicht die Weltanschauung des Menschen.',
    description: 'Tierernährung ohne tierische Bestandteile. Bei Haustieren entscheidet zuerst der Bedarf der Tierart; besonders Katzen sind hier deutlich kritischer als Menschen.',
  },
  {
    key: 'vermehrer',
    title: 'Vermehrer',
    summary: 'Person oder Betrieb, der Tiere vor allem für schnelle Abgabe und Gewinn produziert.',
    description: 'Person oder Betrieb, der Tiere vor allem für schnelle Abgabe, Optik und Gewinn produziert. Gesundheit, Sozialisation, Herkunft und Nachbetreuung bleiben oft auf der Strecke.',
  },
  {
    key: 'veterinaermedizin',
    title: 'Veterinärmedizin',
    summary: 'Tiermedizinische Diagnostik und Behandlung durch Tierärztinnen und Tierärzte.',
    description: 'Tiermedizinische Diagnostik, Behandlung und Vorsorge durch Tierärztinnen und Tierärzte. Sie ist bei Krankheit, Schmerzen und Notfällen nicht durch Glaubensmethoden ersetzbar.',
  },
  {
    key: 'vogelkundiger-tierarzt',
    title: 'Vogelkundiger Tierarzt',
    summary: 'Tierarzt oder Tierärztin mit besonderer Erfahrung in Vogelmedizin. Bei Vögeln oft entscheidend.',
    description: 'Tierarzt oder Tierärztin mit besonderer Erfahrung in Vogelmedizin. Vögel verbergen Krankheiten lange und brauchen häufig spezialisierte Diagnostik; eine normale Kleintierpraxis ist nicht immer ausreichend.',
  },
  {
    key: 'vergiftung',
    title: 'Vergiftung',
    summary: 'Aufnahme oder Kontakt mit giftigen Stoffen. Verpackung sichern und sofort eine Tierarztpraxis oder Tierklinik anrufen.',
    description: 'Aufnahme oder Kontakt mit giftigen Stoffen. Bei Verdacht: Verpackung oder Quelle sichern, Zeitpunkt und Menge notieren und sofort eine Tierarztpraxis oder Tierklinik anrufen.',
  },
  {
    key: 'winterruhe',
    title: 'Winterruhe',
    summary: 'Kontrollierte Ruhephase bei bestimmten Tierarten, etwa europäischen Landschildkröten.',
    description: 'Kontrollierte Ruhephase mit reduziertem Stoffwechsel. Für bestimmte Arten, etwa europäische Landschildkröten, ist sie gesundheitlich notwendig.',
  },
  {
    key: 'xylit',
    title: 'Xylit',
    summary: 'Birkenzucker. Für Hunde kann schon wenig Xylit lebensgefährlich sein.',
    description: 'Birkenzucker, ein Zuckeraustauschstoff. Für Hunde kann Xylit lebensgefährlich sein, weil es schwere Unterzuckerung und Leberschäden auslösen kann.',
  },
  {
    key: 'zoohandel',
    title: 'Zoohandel',
    summary: 'Kommerzieller Verkauf von Tieren und Zubehör. Problematisch, wenn Verkauf vor Tierwohl steht.',
    description: 'Kommerzieller Verkauf von Tieren und Zubehör. Problematisch wird Zoohandel, wenn Beratung, Herkunft, Sozialisation und Langzeitverantwortung hinter dem Verkauf zurückstehen.',
  },
  {
    key: 'zahnfehlstellung',
    title: 'Zahnfehlstellung',
    summary: 'Fehlstellung der Zähne, die Fressen, Atmung, Pflege oder Schmerzfreiheit beeinträchtigen kann.',
    description: 'Fehlstellung der Zähne oder Kiefer. Bei Kaninchen, Meerschweinchen, brachyzephalen Hunden und Qualzuchten können Zahnfehlstellungen Fressen, Atmung, Augen, Pflege und Schmerzfreiheit stark beeinträchtigen.',
  },
  {
    key: 'zoonose',
    title: 'Zoonose',
    summary: 'Krankheit, die zwischen Tier und Mensch übertragen werden kann.',
    description: 'Krankheit, die zwischen Tier und Mensch übertragen werden kann. Beispiele sind Tollwut, Salmonellen, Toxoplasmose oder bestimmte Parasiten.',
  },
  {
    key: 'zuechter',
    title: 'Züchter',
    summary: 'Person, die Tiere gezielt verpaart. Seriöse Zucht ist nicht dasselbe wie Vermehrung, erzeugt aber neue Tiere.',
    description: 'Person, die Tiere gezielt verpaart. Seriöse Zucht arbeitet transparenter als Vermehrung, erzeugt aber trotzdem neue Haustiere in einem überfüllten System.',
  },
  {
    key: 'gefahrtier',
    title: 'Gefahrtier',
    summary: 'Tier, das wegen Größe, Gift, Kraft oder Verhalten besondere Sicherheitsanforderungen stellt.',
    description: 'Tier, das wegen Größe, Gift, Kraft, Jagdverhalten oder Unberechenbarkeit besondere Sicherheitsanforderungen stellt. Die Regeln unterscheiden sich je nach Bundesland.',
  },
  {
    key: 'gefahrtierliste',
    title: 'Gefahrtierliste',
    summary: 'Landes- oder kommunal geregelte Liste von Tierarten, deren Haltung besondere Auflagen haben kann.',
    description: 'Liste von Tierarten, deren Haltung wegen möglicher Gefahren besondere Anforderungen, Erlaubnisse oder Verbote auslösen kann. Gefahrtierlisten sind nicht bundesweit einheitlich, sondern regional geregelt.',
  },
  {
    key: 'thermoregulation',
    title: 'Thermoregulation',
    summary: 'Fähigkeit des Körpers, Temperatur zu halten oder zu steuern. Bei Qualzucht oder Hitze kann sie versagen.',
    description: 'Fähigkeit des Körpers, Temperatur zu halten oder aktiv zu steuern. Bei Hitze, Kurzköpfigkeit, Albinismus oder falscher Haltung kann Thermoregulation massiv eingeschränkt sein.',
  },
];

export const glossaryAnnotationsByPage = {
  startseite: [
    {
      from: 'Goldfischglas, Einzelvogel, Katermythen, <span class="glossary-term" data-glossary-title="Globuli" data-glossary-text="Kleine Zuckerkügelchen aus der Homöopathie. In üblichen Potenzen ist kein Wirkstoff mehr nachweisbar." data-glossary-href="glossar/index.html">Globuli</span>: Was stimmt wirklich?',
      to: `Goldfischglas, Einzelvogel, Katermythen, ${mark('globuli', 'Globuli')}: Was stimmt wirklich?`,
    },
    { from: 'Viele Kleintiere brauchen Fläche, Struktur, Artgenossen und Rückzugsorte', to: `Viele Kleintiere brauchen Fläche, Struktur, ${mark('artgenosse', 'Artgenossen')} und Rückzugsorte` },
    { from: 'Bei Atemnot, Krämpfen, Vergiftungsverdacht oder starken Schmerzen', to: `Bei ${mark('atemnot', 'Atemnot')}, Krämpfen, ${mark('vergiftung', 'Vergiftungsverdacht')} oder starken Schmerzen` },
    {
      from: '<span class="glossary-term" data-glossary-title="Einzeljäger" data-glossary-text="Tiere, die allein jagen. Das heißt nicht automatisch, dass sie allein leben wollen." data-glossary-href="glossar/index.html">Einzeljäger</span>, aber keine Einzelgänger.',
      to: `${mark('einzeljaeger', 'Einzeljäger')}, aber keine ${mark('einzelgaenger', 'Einzelgänger')}.`,
    },
    {
      from: '<span class="glossary-term" data-glossary-title="Schwarmvogel" data-glossary-text="Vogelart, die in Gruppen lebt und zwingend Artgenossen braucht. Einzelhaltung ist bei solchen Arten kein kleiner Kompromiss." data-glossary-href="glossar/index.html">Schwarmtiere</span>, keine Dekoration.',
      to: `${mark('schwarmvogel', 'Schwarmtiere')}, keine Dekoration.`,
    },
    { from: 'Pferde</span><small>Herdentiere, nie Solisten.</small>', to: `Pferde</span><small>${mark('herdentier', 'Herdentiere')}, nie Solisten.</small>` },
    {
      from: '<span class="glossary-term" data-glossary-title="Kastration" data-glossary-text="Chirurgische Entfernung der Keimdrüsen. Verhindert Fortpflanzung und kann hormonbedingten Stress oder Erkrankungen senken." data-glossary-href="glossar/index.html">Kastration</span> nicht mehr aufschiebt',
      to: `${mark('kastration', 'Kastration')} nicht mehr aufschiebt`,
    },
  ],
  mensch: [
    { from: 'Tiere – besonders Beutetiere wie <a href="#voegel"', to: `Tiere – besonders ${mark('beutetier', 'Beutetiere')} wie <a href="#voegel"` },
    { from: 'Es ist kognitive Dissonanz – ein psychologischer Schutzmechanismus.', to: `Es ist ${mark('kognitive-dissonanz', 'kognitive Dissonanz')} – ein psychologischer Schutzmechanismus.` },
    { from: 'Bissverletzungen. FIV. Ein deutlich kürzeres Leben.', to: `Bissverletzungen. ${mark('fiv', 'FIV')}. Ein deutlich kürzeres Leben.` },
    { from: 'Die meisten Tierheimtiere sind dort, weil Menschen versagt haben', to: `Die meisten ${mark('tierheim', 'Tierheimtiere')} sind dort, weil Menschen versagt haben` },
    { from: 'Parvovirose-Behandlung (2.000–5.000 €)', to: `${mark('parvovirose', 'Parvovirose')}-Behandlung (2.000–5.000 €)` },
    { from: 'Verhaltenstherapie wegen Frühentwöhnung', to: `Verhaltenstherapie wegen fehlender ${mark('sozialisation', 'Sozialisation')}` },
  ],
  hunde: [
    { from: 'Kastration beim Rüden: ca. 200–400 Euro, bei der Hündin: ca. 400–800 Euro (GOT 2022).', to: `Kastration beim Rüden: ca. 200–400 Euro, bei der Hündin: ca. 400–800 Euro (${mark('got', 'GOT 2022')}).` },
    { from: 'Kontakt zu anderen Hunden (Sozialverhalten muss gelernt und gepflegt werden)', to: `Kontakt zu anderen Hunden (${mark('sozialisation', 'Sozialverhalten')} muss gelernt und gepflegt werden)` },
    { from: 'Gebärmutterentzündung (<a href="#glossar" onclick="navigateTo(\'glossar\');return false">Pyometra</a>)', to: `Gebärmutterentzündung (${mark('pyometra', 'Pyometra')})` },
    { from: 'Die Kosten nach der aktuellen Gebührenordnung für Tierärzte (GOT 2022):', to: `Die Kosten nach der aktuellen ${mark('got', 'Gebührenordnung für Tierärzte')} (GOT 2022):` },
    { from: 'Die <a href="https://www.gesetze-im-internet.de/tierschhuv/" target="_blank" rel="noopener noreferrer">Tierschutz-Hundeverordnung</a> regelt Mindestanforderungen', to: `Die <a href="https://www.gesetze-im-internet.de/tierschhuv/" target="_blank" rel="noopener noreferrer">${mark('tierschutz-hundeverordnung', 'Tierschutz-Hundeverordnung')}</a> regelt Mindestanforderungen` },
    { from: 'Seit der Reform ist vor allem die Anbindehaltung grundsätzlich verboten.', to: `Seit der Reform ist vor allem die ${mark('anbindehaltung', 'Anbindehaltung')} grundsätzlich verboten.` },
    { from: 'Hüftdysplasie (HD) und Ellbogendysplasie (ED)', to: `${mark('hueftdysplasie', 'Hüftdysplasie (HD)')} und ${mark('ellbogendysplasie', 'Ellbogendysplasie (ED)')}` },
    { from: 'Manche Hunderassen – <a href="#qualzucht" onclick="navigateTo(\'qualzucht\');return false">Möpse, Französische Bulldoggen, Teacup-Hunde</a> –', to: `Manche Hunderassen – <a href="#qualzucht" onclick="navigateTo('qualzucht');return false">${mark('qualzucht', 'Möpse, Französische Bulldoggen, Teacup-Hunde')}</a> –` },
  ],
  katzen: [
    { from: 'Katzen – Einzeljäger, aber keine Einzelgänger', to: `Katzen – ${mark('einzeljaeger', 'Einzeljäger')}, aber keine ${mark('einzelgaenger', 'Einzelgänger')}` },
    { from: 'einen passenden Artgenossen.', to: `einen passenden ${mark('artgenosse', 'Artgenossen')}.` },
    { from: 'Alter, Temperament, Sozialisierung spielen eine große Rolle.', to: `Alter, Temperament, ${mark('sozialisation', 'Sozialisierung')} spielen eine große Rolle.` },
    { from: 'mit Freigang.', to: `mit ${mark('freigang', 'Freigang')}.` },
    { from: 'alle zwei bis drei Wochen rollig', to: `alle zwei bis drei Wochen ${mark('rolligkeit', 'rollig')}` },
    { from: 'ungewollten Trächtigkeit', to: `ungewollten ${mark('traechtigkeit', 'Trächtigkeit')}` },
    { from: 'Anschaffung (Tierheim: Schutzgebühr)', to: `Anschaffung (Tierheim: ${mark('schutzgebuehr', 'Schutzgebühr')})` },
    { from: 'Ich werde die Katze kastrieren und chippen lassen.', to: `Ich werde die Katze ${mark('kastration', 'kastrieren')} und ${mark('chippen', 'chippen')} lassen.` },
    { from: 'Unsauberkeit (außerhalb des Katzenklos urinieren)', to: `${mark('unsauberkeit', 'Unsauberkeit')} (außerhalb des Katzenklos urinieren)` },
  ],
  voegel: [
    { from: 'Vögel – Schwarmtiere, keine Dekoration', to: `Vögel – ${mark('schwarmvogel', 'Schwarmtiere')}, keine Dekoration` },
    { from: 'Vögel brauchen täglich mehrere Stunden Freiflug', to: `Vögel brauchen täglich mehrere Stunden ${mark('freiflug', 'Freiflug')}` },
    { from: 'Vögel sehen UV-Licht', to: `Vögel sehen ${mark('uv-b', 'UV-Licht')}` },
    { from: 'obligat soziale Tiere.', to: `${mark('obligat-sozial', 'obligat soziale Tiere')}.` },
    { from: 'Ich kenne einen vogelkundigen Tierarzt in meiner Nähe.', to: `Ich kenne einen ${mark('vogelkundiger-tierarzt', 'vogelkundigen Tierarzt')} in meiner Nähe.` },
    { from: 'Verhaltensstörungen (Federrupfen, stereotypisches Kopfwippen, Apathie)', to: `Verhaltensstörungen (${mark('stereotypie', 'Federrupfen, stereotypisches Kopfwippen')}, ${mark('apathie', 'Apathie')})` },
    { from: 'sicheren Freiflug in einem vogelsicheren Raum', to: `sicheren ${mark('freiflug', 'Freiflug')} in einem vogelsicheren Raum` },
    { from: 'kein Teflon in der Küche', to: `kein ${mark('ptfe', 'Teflon')} in der Küche` },
  ],
  kleintiere: [
    { from: 'Die meisten Kleintiere sind Fluchttiere.', to: `Die meisten Kleintiere sind ${mark('fluchttier', 'Fluchttiere')}.` },
    { from: 'Platz und Artgenossen.', to: `Platz und ${mark('artgenosse', 'Artgenossen')}.` },
    { from: 'Tierärztliche Vereinigung für Tierschutz (TVT)', to: `${mark('tvt', 'Tierärztliche Vereinigung für Tierschutz (TVT)')}` },
    { from: 'Einzelhaltung verursacht Einsamkeit, Stress und Verhaltensstörungen.', to: `Einzelhaltung verursacht Einsamkeit, Stress und ${mark('stereotypie', 'Verhaltensstörungen')}.` },
    { from: 'Vitamin-C-Mangel führt zu Skorbut.', to: `Vitamin-C-Mangel führt zu ${mark('skorbut', 'Skorbut')}.` },
    { from: 'Falsches Futter führt zu Zahnfehlstellungen', to: `Falsches Futter führt zu ${mark('zahnfehlstellung', 'Zahnfehlstellungen')}` },
    { from: 'Hamster sind nachtaktiv.', to: `Hamster sind ${mark('nachtaktiv', 'nachtaktiv')}.` },
    { from: 'Die meisten Hamsterarten (Goldhamster, Teddyhamster) sind strikte Einzelgänger.', to: `Die meisten Hamsterarten (Goldhamster, Teddyhamster) sind strikte ${mark('einzelgaenger', 'Einzelgänger')}.` },
    { from: 'tagaktive Kolontiere aus Südamerika', to: `tagaktive Kolonietiere aus Südamerika` },
  ],
  exoten: [
    { from: 'Reptilien brauchen UV-B-Strahlung', to: `Reptilien brauchen ${mark('uv-b', 'UV-B-Strahlung')}` },
    { from: 'Temperaturzonen, Luftfeuchtigkeit, UV-Beleuchtung', to: `Temperaturzonen, Luftfeuchtigkeit, ${mark('uv-b', 'UV-Beleuchtung')}` },
    { from: 'erweichen die Knochen (metabolische Knochenerkrankung)', to: `erweichen die Knochen (${mark('metabolische-knochenerkrankung', 'metabolische Knochenerkrankung')})` },
    { from: 'Terrariengröße:', to: `${mark('artgerecht', 'Terrariengröße')}:` },
    { from: 'jährliche Winterruhe', to: `jährliche ${mark('winterruhe', 'Winterruhe')}` },
    { from: 'Washingtoner Artenschutzübereinkommen (CITES)', to: `${mark('cites', 'Washingtoner Artenschutzübereinkommen (CITES)')}` },
    { from: 'geschützt und meldepflichtig', to: `geschützt und ${mark('meldepflicht', 'meldepflichtig')}` },
  ],
  pferde: [
    { from: 'Pferde sind Herdentiere.', to: `Pferde sind ${mark('herdentier', 'Herdentiere')}.` },
    { from: 'Pferde sind Fluchttiere und Herdentiere.', to: `Pferde sind ${mark('fluchttier', 'Fluchttiere')} und ${mark('herdentier', 'Herdentiere')}.` },
    { from: 'Stereotypien (Koppen, Weben, Boxenlaufen) und Apathie', to: `${mark('stereotypie', 'Stereotypien (Koppen, Weben, Boxenlaufen)')} und ${mark('apathie', 'Apathie')}` },
    { from: 'Mindestens ein Artgenosse', to: `Mindestens ein ${mark('artgenosse', 'Artgenosse')}` },
    { from: 'Offenstall/Aktivstall:', to: `${mark('offenstall', 'Offenstall')}/${mark('aktivstall', 'Aktivstall')}:` },
    { from: 'Boxenhaltung:', to: `${mark('boxenhaltung', 'Boxenhaltung')}:` },
    { from: 'Anbindehaltung:', to: `${mark('anbindehaltung', 'Anbindehaltung')}:` },
    { from: 'Hufschmied (alle 6–8 Wochen)', to: `${mark('hufschmied', 'Hufschmied')} (alle 6–8 Wochen)` },
    { from: 'Koliken: 3.000–10.000 Euro', to: `${mark('kolik', 'Koliken')}: 3.000–10.000 Euro` },
    { from: 'Hufreheschübe, chronische Erkrankungen', to: `${mark('hufrehe', 'Hufreheschübe')}, chronische Erkrankungen` },
  ],
  kastration: [
    { from: 'Entfernung der Keimdrüsen', to: `Entfernung der ${mark('keimdruese', 'Keimdrüsen')}` },
    { from: '<strong>Kastration</strong> entfernt die Keimdrüsen', to: `<strong>${mark('kastration', 'Kastration')}</strong> entfernt die ${mark('keimdruese', 'Keimdrüsen')}` },
    { from: '<strong>Sterilisation</strong> durchtrennt nur die Ei-', to: `<strong>${mark('sterilisation', 'Sterilisation')}</strong> durchtrennt nur die Ei-` },
    { from: 'Rammler: Frühkastration empfohlen.', to: `Rammler: ${mark('fruehkastration', 'Frühkastration')} empfohlen.` },
    { from: 'das Tier bleibt rollig, markiert weiter, streunt weiter', to: `das Tier bleibt ${mark('rolligkeit', 'rollig')}, markiert weiter, streunt weiter` },
    { from: 'senkt das Risiko für Mammatumoren deutlich', to: `senkt das Risiko für ${mark('mammatumor', 'Mammatumoren')} deutlich` },
    { from: 'Gebärmutterentzündung (Pyometra)', to: `Gebärmutterentzündung (${mark('pyometra', 'Pyometra')})` },
    { from: 'Kastrations-, Kennzeichnungs- und Registrierungspflicht', to: `${mark('kastrationspflicht', 'Kastrations-')}, ${mark('kennzeichnungspflicht', 'Kennzeichnungs-')} und ${mark('registrierungspflicht', 'Registrierungspflicht')}` },
  ],
  qualzucht: [
    { from: 'Qualzucht bedeutet: Tiere werden auf äußere Merkmale gezüchtet', to: `${mark('qualzucht', 'Qualzucht')} bedeutet: Tiere werden auf äußere ${mark('rassemerkmal', 'Merkmale')} gezüchtet` },
    { from: '§ 11b TierSchG', to: `§ 11b ${mark('tierschg', 'TierSchG')}` },
    { from: '(<a href="#glossar" onclick="navigateTo(\'glossar\');return false">Brachyzephalie</a>)', to: `(${mark('brachyzephalie', 'Brachyzephalie')})` },
    { from: 'chronischer Atemnot (Brachyzephales Atemwegssyndrom)', to: `chronischer Atemnot (${mark('brachyzephales-atemwegssyndrom', 'Brachyzephales Atemwegssyndrom')})` },
    { from: 'eines Gendefekts', to: `eines ${mark('gendefekt', 'Gendefekts')}` },
    { from: 'Osteochondrodysplasie', to: `${mark('osteochondrodysplasie', 'Osteochondrodysplasie')}` },
    { from: 'Gezielte Zucht auf Albinismus.', to: `Gezielte Zucht auf ${mark('albinismus', 'Albinismus')}.` },
    { from: 'natürlichen Thermoregulation', to: `natürlichen ${mark('thermoregulation', 'Thermoregulation')}` },
  ],
  adoption: [
    { from: 'Adoption statt Kauf', to: `${mark('adoption', 'Adoption')} statt Kauf` },
    { from: 'Tierheimtiere sind geimpft, kastriert, gechippt', to: `${mark('tierheim', 'Tierheimtiere')} sind geimpft, kastriert, gechippt` },
    { from: 'Die Schutzgebühr (50–350 Euro je nach Tierart)', to: `Die ${mark('schutzgebuehr', 'Schutzgebühr')} (50–350 Euro je nach Tierart)` },
    { from: 'Tiere aus der Zoohandlung', to: `Tiere aus der ${mark('zoohandel', 'Zoohandlung')}` },
    { from: 'stammen aus Zuchtbetrieben', to: `stammen aus ${mark('vermehrer', 'Zuchtbetrieben')}` },
    { from: 'beim seriösen Züchter', to: `beim seriösen ${mark('zuechter', 'Züchter')}` },
    { from: 'Brachyzephale Hunde', to: `${mark('brachyzephalie', 'Brachyzephale Hunde')}` },
    { from: 'Schutzgebühr und Vertrag.', to: `${mark('schutzgebuehr', 'Schutzgebühr')} und ${mark('schutzvertrag', 'Vertrag')}.` },
    { from: 'Welpen aus osteuropäischen Vermehrerstationen', to: `Welpen aus osteuropäischen ${mark('vermehrer', 'Vermehrerstationen')}` },
    { from: '<strong>Parvovirose</strong>', to: `<strong>${mark('parvovirose', 'Parvovirose')}</strong>` },
    { from: '<strong>Hüftdysplasie</strong>', to: `<strong>${mark('hueftdysplasie', 'Hüftdysplasie')}</strong>` },
    { from: '<strong>Verhaltenstherapie</strong> (weil keine Sozialisierung)', to: `<strong>Verhaltenstherapie</strong> (weil keine ${mark('sozialisation', 'Sozialisierung')})` },
    { from: 'auf einer Pflegestelle', to: `auf einer ${mark('pflegestelle', 'Pflegestelle')}` },
  ],
  selbsttest: [
    { from: 'Hast du Rücklagen für tierärztliche Notfälle?', to: `Hast du Rücklagen für tierärztliche ${mark('notdienst', 'Notfälle')}?` },
    { from: 'Bist du bereit, dein Tier kastrieren zu lassen?', to: `Bist du bereit, dein Tier ${mark('kastration', 'kastrieren')} zu lassen?` },
    { from: 'Notdienste und Spezialisten informiert.', to: `${mark('notdienst', 'Notdienste')} und Spezialisten informiert.` },
    { from: 'artgerechte Einrichtung.', to: `${mark('artgerecht', 'artgerechte')} Einrichtung.` },
  ],
  notfall: [
    { from: 'Bei Atemnot, Krampf, Vergiftungsverdacht', to: `Bei ${mark('atemnot', 'Atemnot')}, ${mark('krampfanfall', 'Krampf')}, ${mark('vergiftung', 'Vergiftungsverdacht')}` },
    { from: 'Harnstopp, Zusammenbruch oder starker Blutung', to: `${mark('harnstopp', 'Harnstopp')}, ${mark('kollaps', 'Zusammenbruch')} oder starker Blutung` },
    { from: 'Speicheln, Apathie nach Kontakt mit Giftquellen', to: `Speicheln, ${mark('apathie', 'Apathie')} nach Kontakt mit Giftquellen` },
    { from: 'Magendrehung = lebensbedrohlich', to: `${mark('magendrehung', 'Magendrehung')} = lebensbedrohlich` },
    { from: 'Harnröhrenverschluss = Notfall', to: `${mark('harnroehrenverschluss', 'Harnröhrenverschluss')} = Notfall` },
    { from: 'Schokolade</strong> (Theobromin)', to: `Schokolade</strong> (${mark('theobromin', 'Theobromin')})` },
    { from: '<strong>Xylit</strong> (Birkenzucker)', to: `<strong>${mark('xylit', 'Xylit')}</strong> (Birkenzucker)` },
    { from: 'lebensbedrohlichem Insulinschock', to: `lebensbedrohlichem ${mark('insulinschock', 'Insulinschock')}` },
    { from: '<strong>Permethrin</strong> (in manchen Hunde-Flohmitteln)', to: `<strong>${mark('permethrin', 'Permethrin')}</strong> (in manchen Hunde-Flohmitteln)` },
    { from: '<strong>Teflon-Dämpfe</strong> (PTFE)', to: `<strong>${mark('ptfe', 'Teflon-Dämpfe (PTFE)')}</strong>` },
    { from: 'Hitzschlag (Hund im Auto, Sommerüberhitzung)', to: `${mark('hitzschlag', 'Hitzschlag')} (Hund im Auto, Sommerüberhitzung)` },
    { from: 'Tierärztlichen Notdienst finden', to: `Tierärztlichen ${mark('notdienst', 'Notdienst')} finden` },
    { from: '<button class="accordion-header" onclick="toggleAccordion(this)">Krampfanfall</button>', to: `<button class="accordion-header" onclick="toggleAccordion(this)">${mark('krampfanfall', 'Krampfanfall')}</button>` },
  ],
  wissen: [
    { from: 'Homöopathie bei Tieren', to: `${mark('homoeopathie', 'Homöopathie')} bei Tieren` },
    { from: 'Globuli kein Tierschutz', to: `${mark('globuli', 'Globuli')} kein Tierschutz` },
    { from: 'systematische Reviews, Metaanalysen', to: `${mark('systematischer-review', 'systematische Reviews')}, ${mark('metaanalyse', 'Metaanalysen')}` },
    { from: 'über den Placebo-Effekt hinaus', to: `über den ${mark('placebo-effekt', 'Placebo-Effekt')} hinaus` },
    { from: 'Die sogenannte Potenzierung', to: `Die sogenannte ${mark('potenzierung', 'Potenzierung')}` },
    { from: 'D23-Verdünnung (die meisten Globuli sind D12, C30 oder höher)', to: `D23-Verdünnung (die meisten Globuli sind ${mark('d-und-c-potenz', 'D12, C30 oder höher')})` },
    { from: 'Tierheilpraktikerin im Dorf', to: `${mark('tierheilpraktiker', 'Tierheilpraktikerin')} im Dorf` },
    { from: 'zum vogelkundigen Tierarzt zu gehen.', to: `zum ${mark('vogelkundiger-tierarzt', 'vogelkundigen Tierarzt')} zu gehen.` },
    { from: 'evidenzbasierter Veterinärmedizin', to: `${mark('evidenzbasierte-medizin', 'evidenzbasierter')} ${mark('veterinaermedizin', 'Veterinärmedizin')}` },
    { from: 'bestimmte Phytotherapie', to: `bestimmte ${mark('phytotherapie', 'Phytotherapie')}` },
    { from: 'Phytotherapie oder Physiotherapie', to: `${mark('phytotherapie', 'Phytotherapie')} oder ${mark('tierphysiotherapie', 'Physiotherapie')}` },
    { from: 'Globuli und Nosoden', to: `Globuli und ${mark('nosoden', 'Nosoden')}` },
    { from: 'Physiotherapie.</strong> Bei Gelenkproblemen', to: `${mark('tierphysiotherapie', 'Physiotherapie')}.</strong> Bei Gelenkproblemen` },
    { from: 'UV-B-Strahlung, Temperaturzonen', to: `${mark('uv-b', 'UV-B-Strahlung')}, Temperaturzonen` },
    { from: 'eine jährliche Winterruhe', to: `eine jährliche ${mark('winterruhe', 'Winterruhe')}` },
  ],
  'noch-nicht-bereit': [
    { from: 'Patenschaften</h3>', to: `${mark('patenschaft', 'Patenschaften')}</h3>` },
    { from: 'Pflegestelle werden</h3>', to: `${mark('pflegestelle', 'Pflegestelle')} werden</h3>` },
    { from: 'Tierschutzorganisationen suchen immer Pflegestellen', to: `Tierschutzorganisationen suchen immer ${mark('pflegestelle', 'Pflegestellen')}` },
    { from: 'Ein Notfallfonds von 1.000–2.000 Euro', to: `Ein ${mark('notfallfonds', 'Notfallfonds')} von 1.000–2.000 Euro` },
    { from: 'Du erzeugst keine Nachfrage bei Vermehrern.', to: `Du erzeugst keine Nachfrage bei ${mark('vermehrer', 'Vermehrern')}.` },
    { from: 'Wenn die Zeit reif ist: Adoption', to: `Wenn die Zeit reif ist: ${mark('adoption', 'Adoption')}` },
  ],
  kontakt: [
    { from: 'Haltung, Adoption und verantwortungsvolle Entscheidungen', to: `Haltung, ${mark('adoption', 'Adoption')} und verantwortungsvolle Entscheidungen` },
    { from: 'Beratung bei Haltungsfragen', to: `Beratung bei ${mark('artgerecht', 'Haltungsfragen')}` },
    { from: 'ersetzt keine tierärztliche Diagnose', to: `ersetzt keine ${mark('veterinaermedizin', 'tierärztliche Diagnose')}` },
    { from: '<span>Ich suche ein Tier zur Adoption oder möchte eins vermitteln</span>', to: `<span>Ich suche ein Tier zur ${mark('adoption', 'Adoption')} oder möchte eins vermitteln</span>` },
  ],
  'tierarzt-notdienst': [
    { from: 'Tierärztlichen Notdienst finden', to: `Tierärztlichen ${mark('notdienst', 'Notdienst')} finden` },
    { from: 'Wenn dein Tier Atemnot, Krämpfe, starke Blutung, Vergiftungsverdacht', to: `Wenn dein Tier ${mark('atemnot', 'Atemnot')}, Krämpfe, starke Blutung, ${mark('vergiftung', 'Vergiftungsverdacht')}` },
    { from: 'oder Harnstopp zeigt', to: `oder ${mark('harnroehrenverschluss', 'Harnstopp')} zeigt` },
    { from: 'Tierklinik telefonisch kontaktieren', to: `${mark('tierklinik', 'Tierklinik')} telefonisch kontaktieren` },
  ],
  'hitzefalle-auto': [
    { from: 'Bei Hitzestress zählt Handeln', to: `Bei ${mark('hitzschlag', 'Hitzestress')} zählt Handeln` },
    { from: 'durch Hecheln:', to: `durch ${mark('hecheln', 'Hecheln')}:` },
    { from: 'Panik oder Apathie', to: `Panik oder ${mark('apathie', 'Apathie')}` },
    { from: 'Das ist ein medizinischer Notfall.', to: `Das ist ein medizinischer ${mark('hitzschlag', 'Notfall')}.` },
    { from: 'Bei Hitzschlag nicht mit Eiswasser schocken.', to: `Bei ${mark('hitzschlag', 'Hitzschlag')} nicht mit Eiswasser schocken.` },
  ],
  'ernaehrung-taurin': [
    { from: '<span>Taurin</span><span>obligater Karnivor</span>', to: `<span>${mark('taurin', 'Taurin')}</span><span>${mark('obligater-karnivor', 'obligater Karnivor')}</span>` },
    { from: 'Katzen sind obligate Karnivoren', to: `Katzen sind ${mark('obligater-karnivor', 'obligate Karnivoren')}` },
    { from: 'Taurin ist für Katzen essenziell', to: `${mark('taurin', 'Taurin')} ist für Katzen essenziell` },
    { from: 'ein vollständiges Alleinfutter', to: `ein vollständiges ${mark('alleinfutter', 'Alleinfutter')}` },
    { from: 'Vegane Hundeernährung', to: `${mark('vegane-tierernaehrung', 'Vegane Hundeernährung')}` },
    { from: 'Vegane Katzenernährung', to: `${mark('vegane-tierernaehrung', 'Vegane Katzenernährung')}` },
  ],
  realhaltung: [
    { from: 'nicht automatisch artgerecht', to: `nicht automatisch ${mark('artgerecht', 'artgerecht')}` },
    { from: 'Gruppen-/Paarhaltung', to: `${mark('obligat-sozial', 'Gruppen-/Paarhaltung')}` },
    { from: 'Freiflug, UV-Licht', to: `${mark('freiflug', 'Freiflug')}, ${mark('uv-b', 'UV-Licht')}` },
    { from: 'Training, Sozialkontakt und Notfallbudget', to: `Training, ${mark('artgenosse', 'Sozialkontakt')} und Notfallbudget` },
    { from: 'Gesetzliche Mindestanforderungen', to: `${mark('tierschg', 'Gesetzliche Mindestanforderungen')}` },
  ],
  'zucht-und-vermehrung': [
    { from: 'Ein seriöser Züchter ist kein Vermehrer.', to: `Ein seriöser ${mark('zuechter', 'Züchter')} ist kein ${mark('vermehrer', 'Vermehrer')}.` },
    { from: 'Vermehrer produzieren Tiere als Ware', to: `${mark('vermehrer', 'Vermehrer')} produzieren Tiere als Ware` },
    { from: 'Seriöse Züchter arbeiten transparenter', to: `Seriöse ${mark('zuechter', 'Züchter')} arbeiten transparenter` },
    { from: 'kontrollierte, dokumentierte Nachzucht', to: `kontrollierte, dokumentierte ${mark('zuechter', 'Nachzucht')}` },
    { from: 'kein Freibrief für Qualzuchtmerkmale', to: `kein Freibrief für ${mark('qualzucht', 'Qualzuchtmerkmale')}` },
    { from: '§ 11 Tierschutzgesetz', to: `§ 11 ${mark('tierschg', 'Tierschutzgesetz')}` },
  ],
  wildtierhaltung: [
    { from: 'Artenschutzrecht kann Herkunft', to: `${mark('artenschutz', 'Artenschutzrecht')} kann Herkunft` },
    { from: 'Herkunft, Nachweise', to: `Herkunft, ${mark('herkunftsnachweis', 'Nachweise')}` },
    { from: 'Meldepflichten betreffen', to: `${mark('meldepflicht', 'Meldepflichten')} betreffen` },
    { from: 'Faszination ersetzt keine Sachkunde', to: `Faszination ersetzt keine ${mark('sachkunde', 'Sachkunde')}` },
    { from: 'Gefahrtierregeln', to: `${mark('gefahrtier', 'Gefahrtierregeln')}` },
    { from: 'Gefahrtierlisten', to: `${mark('gefahrtierliste', 'Gefahrtierlisten')}` },
    { from: 'Brut- und Setzzeiten', to: `${mark('brut-und-setzzeit', 'Brut- und Setzzeiten')}` },
    { from: 'Leinenpflicht, Brut- und Setzzeit', to: `${mark('leinenpflicht', 'Leinenpflicht')}, Brut- und Setzzeit` },
  ],
};
